### ISSUE TITLE
media page

### ISSUE THREAD

**Issue by Salil999** [Salil999/WheelchairBasketball#1]
basically, fix the mobile view and try to simulate as close as you can to the Media.png file in the mockup images. the flat-theme UI I am using is from here: 
http://designmodo.github.io/Flat-UI/
http://designmodo.github.io/Flat-UI/docs/components.html

**Comment by pranaygp** [comment]
@Salil999 I don't see a Media.png or a mockup images directory. 
You may have missed a push. Can you please push your last commit.

**Comment by pranaygp** [comment]
Ignore this. It was in the `dev` branch

**Comment by pranaygp** [comment]
Attempt at implementation with #2 
@Salil999 please review, merge and close issue
